version: 0.2

phases:
  install:
    commands:
      - echo "Installing Angular CLI..."
      - npm install -g @angular/cli@21
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/spending-control-frontend/browser'
